// <auto-generated />
namespace StockStatistics.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addpricedailymodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addpricedailymodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202001170853522_add.pricedaily.model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
